# Generated by Django 5.2.6 on 2025-10-15 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodeusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_usuario', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'tipodeusuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenancy.empresa')),
                ('idtipousuario', models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='users.tipodeusuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='BloqueoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Bloqueo de Usuario',
                'verbose_name_plural': 'Bloqueos de Usuarios',
                'db_table': 'bloqueousuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='tenancy.empresa')),
                ('usuario', models.ForeignKey(blank=True, db_column='codusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
            },
        ),
        migrations.AddConstraint(
            model_name='tipodeusuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'rol'), name='uq_tipousuario_empresa_rol'),
        ),
    ]
