# Generated by Django 5.2.6 on 2025-10-16 04:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEmpresaMN',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanalNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'canalnotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaMN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('codpaciente', models.IntegerField()),
                ('cododontologo', models.IntegerField(null=True)),
                ('codrecepcionista', models.IntegerField(null=True)),
                ('idhorario', models.IntegerField()),
                ('idtipoconsulta', models.IntegerField()),
                ('idestadoconsulta', models.IntegerField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivoMovilMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_fcm', models.TextField()),
                ('plataforma', models.CharField(max_length=20)),
                ('modelo_dispositivo', models.CharField(max_length=100, null=True)),
                ('version_app', models.CharField(max_length=20, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
                ('ultima_actividad', models.DateTimeField()),
                ('codusuario', models.IntegerField()),
            ],
            options={
                'db_table': 'dispositivomovil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('fecha_lectura', models.DateTimeField(null=True)),
                ('error_mensaje', models.TextField(null=True)),
                ('intentos', models.IntegerField()),
                ('codusuario', models.IntegerField()),
                ('idtiponotificacion', models.BigIntegerField()),
                ('idcanalnotificacion', models.BigIntegerField()),
                ('iddispositivomovil', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'historialnotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioMN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tiponotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioMN',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('idtipousuario', models.IntegerField()),
                ('notificaciones_email', models.BooleanField()),
                ('notificaciones_push', models.BooleanField()),
                ('recibir_notificaciones', models.BooleanField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('email', 'Correo Electrónico'), ('push', 'Notificación Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Canal de Notificación',
                'verbose_name_plural': 'Canales de Notificación',
                'db_table': 'canalnotificacion',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdominio para acceso multi-tenant (ej: clinica1, clinica2)', max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID del cliente en Stripe', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción en Stripe', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'api_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Tipodeusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_usuario', to='api.empresa')),
            ],
            options={
                'db_table': 'tipodeusuario',
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificación',
                'db_table': 'tiponotificacion',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.empresa')),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Estadodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_consulta', to='api.empresa')),
            ],
            options={
                'db_table': 'estadodeconsulta',
            },
        ),
        migrations.CreateModel(
            name='Estadodefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_factura', to='api.empresa')),
            ],
            options={
                'db_table': 'estadodefactura',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='api.empresa')),
                ('idestadofactura', models.ForeignKey(db_column='idestadofactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadodefactura')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('motivoconsulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('episodio', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='api.empresa')),
            ],
            options={
                'db_table': 'historialclinico',
                'ordering': ['-fecha', '-episodio'],
            },
        ),
        migrations.CreateModel(
            name='Documentoadjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredocumento', models.CharField(max_length=255)),
                ('rutaarchivo', models.CharField(max_length=512)),
                ('fechacreacion', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentosAdjuntos', to='api.empresa')),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='api.historialclinico')),
            ],
            options={
                'db_table': 'documentoadjunto',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.empresa')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('unidaddemedida', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='api.empresa')),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Itemdefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsFacturas', to='api.empresa')),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
            ],
            options={
                'db_table': 'itemdefactura',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidadmiligramos', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='api.empresa')),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('experienciaprofesional', models.TextField(blank=True, null=True)),
                ('nromatricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontologos', to='api.empresa')),
            ],
            options={
                'db_table': 'odontologo',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('carnetidentidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.empresa')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='DispositivoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.TextField(unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('modelo_dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('version_app', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='codusuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo Móvil',
                'verbose_name_plural': 'Dispositivos Móviles',
                'db_table': 'dispositivomovil',
            },
        ),
        migrations.CreateModel(
            name='BloqueoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Bloqueo de Usuario',
                'verbose_name_plural': 'Bloqueos de Usuarios',
                'db_table': 'bloqueousuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='api.empresa')),
                ('usuario', models.ForeignKey(blank=True, db_column='codusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Piezadental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepieza', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_dentales', to='api.empresa')),
            ],
            options={
                'db_table': 'piezadental',
            },
        ),
        migrations.CreateModel(
            name='Plandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaplan', models.DateField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montototal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planesTratamientos', to='api.empresa')),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estado')),
                ('cododontologo', models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente')),
            ],
            options={
                'db_table': 'plandetratamiento',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.plandetratamiento'),
        ),
        migrations.CreateModel(
            name='Recetamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='api.empresa')),
                ('cododontologo', models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente')),
            ],
            options={
                'db_table': 'recetamedica',
            },
        ),
        migrations.CreateModel(
            name='Imtemreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologia', models.TextField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsReceta', to='api.empresa')),
                ('idmedicamento', models.ForeignKey(db_column='idmedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.medicamento')),
                ('idreceta', models.ForeignKey(db_column='idreceta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.recetamedica')),
            ],
            options={
                'db_table': 'itemreceta',
            },
        ),
        migrations.CreateModel(
            name='Registroodontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrosOdontogramas', to='api.empresa')),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='api.historialclinico')),
                ('idpiezadental', models.ForeignKey(db_column='idpiezadental', on_delete=django.db.models.deletion.DO_NOTHING, to='api.piezadental')),
            ],
            options={
                'db_table': 'registroodontograma',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costobase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.empresa')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Itemplandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costofinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsPlanesTratamientos', to='api.empresa')),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estado')),
                ('idpiezadental', models.ForeignKey(blank=True, db_column='idpiezadental', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.piezadental')),
                ('idplantratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.plandetratamiento')),
                ('idservicio', models.ForeignKey(db_column='idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='api.servicio')),
            ],
            options={
                'db_table': 'itemplandetratamiento',
            },
        ),
        migrations.CreateModel(
            name='Tipodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconsulta', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consulta', to='api.empresa')),
            ],
            options={
                'db_table': 'tipodeconsulta',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodeusuario'),
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('canal_notificacion', models.ForeignKey(db_column='idcanalnotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.canalnotificacion')),
                ('usuario', models.ForeignKey(db_column='codusuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('tipo_notificacion', models.ForeignKey(db_column='idtiponotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'preferencianotificacion',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asunto_template', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_template', models.CharField(max_length=200)),
                ('mensaje_template', models.TextField()),
                ('variables_disponibles', models.JSONField(default=list, help_text='Lista de variables disponibles como {nombre}, {fecha}, etc.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('canal_notificacion', models.ForeignKey(db_column='idcanalnotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.canalnotificacion')),
                ('tipo_notificacion', models.ForeignKey(db_column='idtiponotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'plantillanotificacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('canal_notificacion', models.ForeignKey(db_column='idcanalnotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.canalnotificacion')),
                ('dispositivo_movil', models.ForeignKey(blank=True, db_column='iddispositivomovil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dispositivomovil')),
                ('usuario', models.ForeignKey(db_column='codusuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('tipo_notificacion', models.ForeignKey(db_column='idtiponotificacion', on_delete=django.db.models.deletion.CASCADE, to='api.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'db_table': 'historialnotificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pago', to='api.empresa')),
            ],
            options={
                'db_table': 'tipopago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.empresa')),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
                ('idtipopago', models.ForeignKey(db_column='idtipopago', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosultas', to='api.empresa')),
                ('idestadoconsulta', models.ForeignKey(db_column='idestadoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadodeconsulta')),
                ('idhorario', models.ForeignKey(db_column='idhorario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.horario')),
                ('idtipoconsulta', models.ForeignKey(db_column='idtipoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodeconsulta')),
                ('cododontologo', models.ForeignKey(blank=True, db_column='cododontologo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paciente')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='pacientecodigo',
            field=models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historias', to='api.paciente'),
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('radiografia', 'Radiografía'), ('examen_laboratorio', 'Examen de Laboratorio'), ('imagen_diagnostico', 'Imagen de Diagnóstico'), ('consentimiento', 'Consentimiento Informado'), ('receta', 'Receta Médica'), ('foto_clinica', 'Foto Clínica'), ('otro', 'Otro')], max_length=50)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_s3', models.CharField(max_length=500)),
                ('s3_key', models.CharField(max_length=500)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('fecha_documento', models.DateField(help_text='Fecha del documento médico')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idconsulta', models.ForeignKey(blank=True, db_column='idconsulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='api.consulta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='api.empresa')),
                ('idhistorialclinico', models.ForeignKey(blank=True, db_column='idhistorialclinico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_s3', to='api.historialclinico')),
                ('profesional_carga', models.ForeignKey(db_column='profesional_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to='api.usuario')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='api.paciente')),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'db_table': 'documento_clinico',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto_contenido', models.TextField()),
                ('firma_base64', models.TextField(help_text='Firma del paciente guardada en formato Base64')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField()),
                ('pdf_firmado', models.BinaryField(help_text='PDF del consentimiento con firma digital', null=True)),
                ('hash_documento', models.CharField(help_text='Hash SHA-256 del documento firmado', max_length=64, null=True)),
                ('fecha_hora_sello', models.DateTimeField(help_text='Fecha y hora del sellado digital', null=True)),
                ('fecha_validacion', models.DateTimeField(help_text='Fecha y hora de validación', null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.consulta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.empresa')),
                ('validado_por', models.ForeignKey(help_text='Usuario que validó el consentimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_validados', to='api.usuario')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.plandetratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.paciente')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'db_table': 'api_consentimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.usuario')),
                ('habilidadessoftware', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionistas', to='api.empresa')),
            ],
            options={
                'db_table': 'recepcionista',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='codrecepcionista',
            field=models.ForeignKey(blank=True, db_column='codrecepcionista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.recepcionista'),
        ),
        migrations.AddConstraint(
            model_name='tipodeusuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'rol'), name='uq_tipousuario_empresa_rol'),
        ),
        migrations.AlterUniqueTogether(
            name='preferencianotificacion',
            unique_together={('usuario', 'tipo_notificacion', 'canal_notificacion')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillanotificacion',
            unique_together={('tipo_notificacion', 'canal_notificacion')},
        ),
        migrations.AddConstraint(
            model_name='historialclinico',
            constraint=models.UniqueConstraint(fields=('pacientecodigo', 'episodio'), name='uniq_historial_paciente_episodio'),
        ),
    ]
