# Generated by Django 5.2.7 on 2025-10-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el servicio está disponible para ser consultado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(default=30, help_text='Duración estimada del servicio en minutos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
