# Generated by Django 5.2.7 on 2025-10-19 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servicio_options_servicio_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandetratamiento',
            options={'ordering': ['-fechaplan'], 'verbose_name': 'Plan de Tratamiento', 'verbose_name_plural': 'Planes de Tratamiento'},
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='aceptacion_tipo',
            field=models.CharField(blank=True, choices=[('Total', 'Aceptación Total'), ('Parcial', 'Aceptación Parcial')], help_text='Tipo de aceptación: Total (todos los ítems) o Parcial (solo algunos ítems).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='es_editable',
            field=models.BooleanField(default=True, help_text='Indica si el presupuesto puede ser editado. Se bloquea al ser aceptado.'),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='estado_aceptacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Caducado', 'Caducado'), ('Parcial', 'Aceptación Parcial')], default='Pendiente', help_text='Estado de aceptación del presupuesto por parte del paciente.', max_length=20),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el paciente aceptó el presupuesto.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual el presupuesto es válido. Después de esta fecha, caduca automáticamente.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='firma_digital',
            field=models.TextField(blank=True, help_text='Firma digital del paciente en formato JSON. Incluye timestamp, IP, user agent, etc.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='usuario_acepta',
            field=models.ForeignKey(blank=True, help_text='Usuario (paciente) que aceptó el presupuesto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_aceptados', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='AceptacionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp exacto de la aceptación.')),
                ('tipo_aceptacion', models.CharField(choices=[('Total', 'Aceptación Total'), ('Parcial', 'Aceptación Parcial')], help_text='Tipo de aceptación: Total o Parcial.', max_length=20)),
                ('items_aceptados', models.JSONField(default=list, help_text='Lista de IDs de items (Itemplandetratamiento) aceptados. Vacío si aceptación total.')),
                ('firma_digital', models.JSONField(help_text='Firma digital en formato JSON: {timestamp, user_id, hash, etc.}')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la aceptación.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador/app del paciente.', null=True)),
                ('comprobante_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del comprobante de aceptación. Usado para verificación.', unique=True)),
                ('comprobante_url', models.URLField(blank=True, help_text='URL del PDF del comprobante (si se generó).', max_length=500, null=True)),
                ('monto_total_aceptado', models.DecimalField(decimal_places=2, help_text='Monto total del presupuesto al momento de la aceptación.', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Notas o comentarios adicionales del paciente.', null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_presupuestos', to='api.empresa')),
                ('plandetratamiento', models.ForeignKey(help_text='Presupuesto/Plan de tratamiento aceptado.', on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones', to='api.plandetratamiento')),
                ('usuario_paciente', models.ForeignKey(help_text='Usuario (paciente) que realizó la aceptación.', on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_realizadas', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Aceptación de Presupuesto',
                'verbose_name_plural': 'Aceptaciones de Presupuestos',
                'db_table': 'aceptacionpresupuesto',
                'ordering': ['-fecha_aceptacion'],
                'indexes': [models.Index(fields=['plandetratamiento', 'fecha_aceptacion'], name='aceptacionp_plandet_151f02_idx'), models.Index(fields=['usuario_paciente', 'fecha_aceptacion'], name='aceptacionp_usuario_9c142f_idx'), models.Index(fields=['comprobante_id'], name='aceptacionp_comprob_c9c811_idx')],
            },
        ),
    ]
