# Generated by Django 5.2.6 on 2025-10-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_saas_multitenancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Subdominio para acceso multi-tenant (ej: clinica1, clinica2)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='api_empresa',
        ),
    ]
