# Generated by Django - Multi-tenancy fix for catalog models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_subdomain_and_activo_to_empresa'),
    ]

    operations = [
        # Agregar campo empresa a modelos de catálogo
        migrations.AddField(
            model_name='medicamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='piezadental',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_dentales', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='horario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estadodeconsulta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_consulta', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='estadodefactura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_factura', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consulta', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipodeusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_usuario', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pago', to='api.empresa'),
        ),
    ]