# Generated by Django 5.2.7 on 2025-10-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aceptacion_presupuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='estado_item',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], default='Activo', help_text='Estado del item en el plan (Activo/Cancelado/Completado)', max_length=20),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se canceló el item', null=True),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se completó el tratamiento', null=True),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='fecha_objetivo',
            field=models.DateField(blank=True, help_text='Fecha objetivo para realizar este tratamiento', null=True),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Notas adicionales sobre el item (prioridad, condiciones, etc.)'),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario (profesional) que aprobó el plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_aprobados', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='estado_plan',
            field=models.CharField(choices=[('Borrador', 'Borrador (Editable)'), ('Aprobado', 'Aprobado (Inmutable)'), ('Cancelado', 'Cancelado')], default='Borrador', help_text='Estado del plan: Borrador (editable), Aprobado (inmutable), Cancelado.', max_length=20),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el plan fue aprobado (pasó de Borrador a Aprobado).', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas o comentarios del profesional sobre el plan de tratamiento.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='plan_origen_id',
            field=models.IntegerField(blank=True, help_text='ID del plan original si este es una duplicación/nueva versión.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal calculado de todos los ítems activos del plan.', max_digits=10),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de descuentos aplicados al plan.', max_digits=10),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='version',
            field=models.IntegerField(default=1, help_text='Versión del plan. Se incrementa al aprobar o duplicar.'),
        ),
        migrations.AlterField(
            model_name='itemplandetratamiento',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.plandetratamiento'),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='montototal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
