# Generated by Django 5.2.6 on 2025-10-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_lifecycle_sp3_t001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemplandetratamiento',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de Plan de Tratamiento', 'verbose_name_plural': 'Ítems de Planes de Tratamiento'},
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='costo_base_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo base del servicio al momento de agregar al plan (para histórico).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='notas_item',
            field=models.TextField(blank=True, help_text='Notas específicas del item (observaciones, instrucciones, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de ejecución del item en el plan (0 = sin orden específico).'),
        ),
        migrations.AddField(
            model_name='itemplandetratamiento',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo estimado en minutos para el procedimiento.', null=True),
        ),
        # Remove obsolete fields from migration 0004
        migrations.RemoveField(
            model_name='itemplandetratamiento',
            name='fecha_cancelacion',
        ),
        migrations.RemoveField(
            model_name='itemplandetratamiento',
            name='fecha_completado',
        ),
        migrations.RemoveField(
            model_name='itemplandetratamiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='plandetratamiento',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='plandetratamiento',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='plandetratamiento',
            name='plan_origen_id',
        ),
        migrations.RemoveField(
            model_name='plandetratamiento',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='plandetratamiento',
            name='total_descuentos',
        ),
        # Alter fields that already exist from migration 0004 but need different definitions
        migrations.AlterField(
            model_name='itemplandetratamiento',
            name='estado_item',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo (Habilita agenda)'), ('Cancelado', 'Cancelado (No impacta total)'), ('Completado', 'Completado')], default='Pendiente', help_text='Estado del item: Pendiente/Activo/Cancelado/Completado.', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemplandetratamiento',
            name='fecha_objetivo',
            field=models.DateField(blank=True, help_text='Fecha objetivo/estimada para realizar este procedimiento.', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='notas_plan',
            field=models.TextField(blank=True, help_text='Notas generales del plan de tratamiento (diagnóstico, observaciones, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='subtotal_calculado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal calculado automáticamente sumando items activos.', max_digits=10),
        ),
        migrations.AddField(
            model_name='plandetratamiento',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, help_text='Usuario (odontólogo) que aprobó el plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_aprobados', to='api.usuario'),
        ),
        # Alter fields that already exist from migration 0004
        migrations.AlterField(
            model_name='plandetratamiento',
            name='estado_plan',
            field=models.CharField(choices=[('Borrador', 'Borrador (Editable)'), ('Aprobado', 'Aprobado (Inmutable)'), ('Cancelado', 'Cancelado')], default='Borrador', help_text='Estado del plan: Borrador (editable) o Aprobado (inmutable).', max_length=20),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el plan fue aprobado por el odontólogo.', null=True),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Versión del plan. Se incrementa con cada aprobación de cambios mayores.'),
        ),
        migrations.AlterField(
            model_name='itemplandetratamiento',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemplandetratamiento_set', to='api.plandetratamiento'),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plandetratamiento',
            name='montototal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
