# Generated by Django 5.2.6 on 2025-10-12 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('radiografia', 'Radiografía'), ('examen_laboratorio', 'Examen de Laboratorio'), ('imagen_diagnostico', 'Imagen de Diagnóstico'), ('consentimiento', 'Consentimiento Informado'), ('receta', 'Receta Médica'), ('foto_clinica', 'Foto Clínica'), ('otro', 'Otro')], max_length=50)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_s3', models.CharField(max_length=500)),
                ('s3_key', models.CharField(max_length=500)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('fecha_documento', models.DateField(help_text='Fecha del documento médico')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='api.paciente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='api.empresa')),
                ('idconsulta', models.ForeignKey(blank=True, db_column='idconsulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='api.consulta')),
                ('idhistorialclinico', models.ForeignKey(blank=True, db_column='idhistorialclinico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_s3', to='api.historialclinico')),
                ('profesional_carga', models.ForeignKey(db_column='profesional_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'db_table': 'documento_clinico',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
