# Generated by Django 5.2.6 on 2025-10-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documentoclinico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEmpresaMN',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanalNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'canalnotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaMN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('codpaciente', models.IntegerField()),
                ('cododontologo', models.IntegerField(null=True)),
                ('codrecepcionista', models.IntegerField(null=True)),
                ('idhorario', models.IntegerField()),
                ('idtipoconsulta', models.IntegerField()),
                ('idestadoconsulta', models.IntegerField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivoMovilMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_fcm', models.TextField()),
                ('plataforma', models.CharField(max_length=20)),
                ('modelo_dispositivo', models.CharField(max_length=100, null=True)),
                ('version_app', models.CharField(max_length=20, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
                ('ultima_actividad', models.DateTimeField()),
                ('codusuario', models.IntegerField()),
            ],
            options={
                'db_table': 'dispositivomovil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('fecha_lectura', models.DateTimeField(null=True)),
                ('error_mensaje', models.TextField(null=True)),
                ('intentos', models.IntegerField()),
                ('codusuario', models.IntegerField()),
                ('idtiponotificacion', models.BigIntegerField()),
                ('idcanalnotificacion', models.BigIntegerField()),
                ('iddispositivomovil', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'historialnotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioMN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacionMN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tiponotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioMN',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('idtipousuario', models.IntegerField()),
                ('notificaciones_email', models.BooleanField()),
                ('notificaciones_push', models.BooleanField()),
                ('recibir_notificaciones', models.BooleanField()),
                ('empresa_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto_contenido', models.TextField()),
                ('firma_base64', models.TextField(help_text='Firma del paciente guardada en formato Base64')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField()),
                ('pdf_firmado', models.BinaryField(help_text='PDF del consentimiento con firma digital', null=True)),
                ('hash_documento', models.CharField(help_text='Hash SHA-256 del documento firmado', max_length=64, null=True)),
                ('fecha_hora_sello', models.DateTimeField(help_text='Fecha y hora del sellado digital', null=True)),
                ('fecha_validacion', models.DateTimeField(help_text='Fecha y hora de validación', null=True)),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'db_table': 'api_consentimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='tipodeusuario',
            name='rol',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tipodeusuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'rol'), name='uq_tipousuario_empresa_rol'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.consulta'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='api.plandetratamiento'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='validado_por',
            field=models.ForeignKey(help_text='Usuario que validó el consentimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_validados', to='api.usuario'),
        ),
    ]
