# Generated by Django 5.2.7 on 2025-10-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_presupuesto_digital_sp3_t002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplandetratamiento',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='itemplandetratamiento_set', to='api.plandetratamiento'),
        ),
    ]
