# Generated by Django 5.2.7 on 2025-10-26 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_itemplandetratamiento_idplantratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestodigital',
            name='comprobante_aceptacion_url',
            field=models.URLField(blank=True, help_text='URL del PDF del comprobante de aceptación.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='presupuestodigital',
            name='estado_aceptacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de aceptación'), ('Aceptado', 'Aceptado por paciente'), ('Rechazado', 'Rechazado por paciente'), ('Parcial', 'Aceptación parcial (por ítems)')], default='Pendiente', help_text='Estado de aceptación del presupuesto por el paciente.', max_length=20),
        ),
        migrations.AddField(
            model_name='presupuestodigital',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el paciente aceptó el presupuesto.', null=True),
        ),
        migrations.AddField(
            model_name='presupuestodigital',
            name='tipo_aceptacion',
            field=models.CharField(blank=True, choices=[('Total', 'Total'), ('Parcial', 'Parcial')], help_text='Tipo de aceptación: Total o Parcial (por ítems).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='presupuestodigital',
            name='usuario_acepta',
            field=models.ForeignKey(blank=True, help_text='Usuario (paciente) que aceptó el presupuesto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_digitales_aceptados', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='AceptacionPresupuestoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp exacto de la aceptación (sello de tiempo).')),
                ('tipo_aceptacion', models.CharField(choices=[('Total', 'Aceptación Total'), ('Parcial', 'Aceptación Parcial por Ítems')], help_text='Tipo de aceptación: Total o Parcial.', max_length=20)),
                ('items_aceptados', models.JSONField(default=list, help_text='Lista de IDs de ItemPresupuestoDigital aceptados. Vacío si Total.')),
                ('firma_digital', models.JSONField(help_text="\n        Firma digital del paciente en formato JSON:\n        {\n            'timestamp': '2025-10-25T10:30:00Z',\n            'user_id': 123,\n            'signature_hash': 'abc123...',\n            'consent_text': 'Acepto los términos...',\n            'ip_address': '192.168.1.1',\n            'user_agent': 'Mozilla/5.0...'\n        }\n        ")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la aceptación.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador/dispositivo del paciente.', null=True)),
                ('comprobante_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del comprobante para verificación.', unique=True)),
                ('comprobante_url', models.URLField(blank=True, help_text='URL del PDF del comprobante de aceptación.', max_length=500, null=True)),
                ('monto_subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del presupuesto al momento de la aceptación.', max_digits=10)),
                ('monto_descuento', models.DecimalField(decimal_places=2, help_text='Descuento del presupuesto al momento de la aceptación.', max_digits=10)),
                ('monto_total_aceptado', models.DecimalField(decimal_places=2, help_text='Monto total aceptado (snapshot inmutable).', max_digits=10)),
                ('notas_paciente', models.TextField(blank=True, help_text='Comentarios o condiciones del paciente al aceptar.', null=True)),
                ('listo_para_pago', models.BooleanField(default=True, help_text='Indica si está listo para procesar pago.')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa (clínica) asociada al presupuesto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_presupuestos_digitales', to='api.empresa')),
                ('presupuesto_digital', models.ForeignKey(help_text='Presupuesto digital aceptado por el paciente.', on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones', to='api.presupuestodigital')),
                ('usuario_paciente', models.ForeignKey(help_text='Paciente que realizó la aceptación.', on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_presupuestos_digitales', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Aceptación de Presupuesto Digital',
                'verbose_name_plural': 'Aceptaciones de Presupuestos Digitales',
                'db_table': 'aceptacion_presupuesto_digital',
                'ordering': ['-fecha_aceptacion'],
                'indexes': [models.Index(fields=['presupuesto_digital', 'fecha_aceptacion'], name='aceptacion__presupu_8f8246_idx'), models.Index(fields=['usuario_paciente', 'fecha_aceptacion'], name='aceptacion__usuario_8a3f70_idx'), models.Index(fields=['comprobante_id'], name='aceptacion__comprob_aa05fb_idx'), models.Index(fields=['empresa', 'fecha_aceptacion'], name='aceptacion__empresa_bf201c_idx')],
            },
        ),
    ]
