# Generated by Django 5.2.6 on 2025-10-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agregar_aceptacion_presupuesto_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del combo (ej: 'Paquete Blanqueamiento Completo')", max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del combo', null=True)),
                ('tipo_precio', models.CharField(choices=[('PORCENTAJE', 'Descuento Porcentual'), ('MONTO_FIJO', 'Monto Fijo'), ('PROMOCION', 'Precio Promocional')], default='PORCENTAJE', help_text='Tipo de regla de precio aplicada al combo', max_length=20)),
                ('valor_precio', models.DecimalField(decimal_places=2, help_text='Valor según tipo_precio: % de descuento, monto fijo, o precio promocional', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el combo está disponible para su uso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos_servicios', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Combo de Servicios',
                'verbose_name_plural': 'Combos de Servicios',
                'db_table': 'combo_servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComboServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de veces que se incluye este servicio en el combo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación del servicio en el combo')),
                ('combo', models.ForeignKey(help_text='Combo al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.comboservicio')),
                ('servicio', models.ForeignKey(help_text='Servicio incluido en el combo', on_delete=django.db.models.deletion.PROTECT, related_name='combos_detalle', to='api.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Combo',
                'verbose_name_plural': 'Detalles de Combos',
                'db_table': 'combo_servicio_detalle',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='comboservicio',
            constraint=models.CheckConstraint(condition=models.Q(('valor_precio__gte', 0)), name='combo_valor_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='comboserviciodetalle',
            constraint=models.UniqueConstraint(fields=('combo', 'servicio'), name='unique_combo_servicio'),
        ),
        migrations.AddConstraint(
            model_name='comboserviciodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='combo_detalle_cantidad_positiva'),
        ),
    ]
