# Generated by Django 5.2.6 on 2025-10-27 21:19

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plandetratamiento_progreso_general_sesiontratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo subido (imagen o PDF)', max_length=500, upload_to=api.models.evidencia_upload_path)),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('tipo', models.CharField(choices=[('evidencia_sesion', 'Evidencia de Sesión'), ('radiografia', 'Radiografía'), ('foto_clinica', 'Foto Clínica'), ('documento', 'Documento')], default='evidencia_sesion', help_text='Tipo de evidencia', max_length=50)),
                ('mimetype', models.CharField(help_text='MIME type del archivo (ej: image/jpeg)', max_length=100)),
                ('tamanio', models.IntegerField(help_text='Tamaño en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida')),
                ('ip_subida', models.GenericIPAddressField(blank=True, help_text='IP desde donde se subió el archivo', null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa (tenant) dueña de la evidencia', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.empresa')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario que subió la evidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['empresa', '-fecha_subida'], name='evidencias_empresa_361b5f_idx'), models.Index(fields=['usuario', '-fecha_subida'], name='evidencias_usuario_ba7f7c_idx'), models.Index(fields=['tipo', '-fecha_subida'], name='evidencias_tipo_054c7c_idx')],
            },
        ),
    ]
