# Generated by Django 5.2.7 on 2025-10-28 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pagos_en_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoenlinea',
            name='consulta',
            field=models.ForeignKey(blank=True, help_text='Consulta si el origen es cita', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='api.consulta'),
        ),
        migrations.AlterField(
            model_name='pagoenlinea',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, help_text='Plan de tratamiento si el origen es plan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='api.plandetratamiento'),
        ),
    ]
