# Generated by Django 5.2.7 on 2025-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_optimize_estado_to_8_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='hora_preferida',
        ),
        migrations.AddField(
            model_name='consulta',
            name='agendado_por_web',
            field=models.BooleanField(db_column='agendado_por_web', default=False, help_text='¿Esta consulta fue agendada por el paciente desde la web?'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_preferido',
            field=models.CharField(choices=[('mañana', 'Mañana (8am-12pm)'), ('tarde', 'Tarde (2pm-6pm)'), ('noche', 'Noche (6pm-8pm)'), ('cualquiera', 'Cualquier horario')], db_column='horario_preferido', default='cualquiera', help_text='Horario preferido por el paciente', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], db_column='prioridad', default='normal', help_text='Nivel de prioridad de la consulta', max_length=20),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='duracion_estimada',
            field=models.IntegerField(db_column='duracion_estimada', default=30, help_text='Duración estimada de la consulta en minutos'),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='es_urgencia',
            field=models.BooleanField(db_column='es_urgencia', default=False, help_text='¿Es un tipo de consulta urgente? (prioridad alta, notificación inmediata)'),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='permite_agendamiento_web',
            field=models.BooleanField(db_column='permite_agendamiento_web', default=False, help_text='¿Los pacientes pueden agendar este tipo de consulta desde la web?'),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='requiere_aprobacion',
            field=models.BooleanField(db_column='requiere_aprobacion', default=False, help_text='¿Requiere aprobación de staff antes de confirmar?'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_consulta', 'En Consulta'), ('diagnosticada', 'Diagnosticada'), ('con_plan', 'Con Plan'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', help_text='Estado del ciclo de vida de la cita', max_length=20),
        ),
    ]
