# Generated by Django 5.2.7 on 2025-10-29 17:09

from django.db import migrations, models
from django.utils import timezone


def set_default_timestamps(apps, schema_editor):
    """
    Establecer timestamps para consultas existentes.
    Para consultas existentes, usamos la fecha de la consulta como aproximación.
    """
    Consulta = apps.get_model('api', 'Consulta')
    now = timezone.now()
    
    # Actualizar consultas existentes
    for consulta in Consulta.objects.all():
        # Usar la fecha de la consulta como aproximación para created_at
        # Si tiene hora_inicio_consulta, usar esa
        if consulta.hora_inicio_consulta:
            consulta.created_at = consulta.hora_inicio_consulta
        elif consulta.fecha_consulta:
            # Combinar fecha_consulta con hora actual
            consulta.created_at = timezone.make_aware(
                timezone.datetime.combine(consulta.fecha_consulta, timezone.datetime.min.time())
            )
        else:
            # Usar fecha del campo fecha
            consulta.created_at = timezone.make_aware(
                timezone.datetime.combine(consulta.fecha, timezone.datetime.min.time())
            )
        
        consulta.updated_at = now
        consulta.save(update_fields=['created_at', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_agendamiento_web'),
    ]

    operations = [
        # Agregar campo created_at (auto_now_add=True)
        migrations.AddField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,  # Temporal para permitir migración
                help_text='Fecha y hora de creación de la consulta'
            ),
        ),
        # Agregar campo updated_at (auto_now=True)
        migrations.AddField(
            model_name='consulta',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                null=True,  # Temporal para permitir migración
                help_text='Fecha y hora de última actualización'
            ),
        ),
        # Establecer valores para consultas existentes
        migrations.RunPython(
            set_default_timestamps,
            reverse_code=migrations.RunPython.noop
        ),
        # Hacer campos no nulos (ya tienen valores)
        migrations.AlterField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Fecha y hora de creación de la consulta'
            ),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Fecha y hora de última actualización'
            ),
        ),
    ]
