# Generated by Django 5.2.6 on 2025-10-16 04:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaNoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('penalizacion_economica', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bloqueo_temporal', models.BooleanField(default=False)),
                ('reprogramacion_obligatoria', models.BooleanField(default=False)),
                ('alerta_interna', models.BooleanField(default=False)),
                ('notificacion_paciente', models.BooleanField(default=False)),
                ('notificacion_profesional', models.BooleanField(default=False)),
                ('dias_bloqueo', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('estado_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadodeconsulta')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.consulta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.usuario')),
                ('politica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_aplicadas', to='no_show_policies.politicanoshow')),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('consulta', 'politica'), name='uniq_multa_por_consulta_y_politica')],
            },
        ),
    ]
