# Generated by Django 5.2.6 on 2025-10-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaNoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('estado_consulta', models.CharField(max_length=50)),
                ('penalizacion_economica', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bloqueo_temporal', models.BooleanField(default=False)),
                ('reprogramacion_obligatoria', models.BooleanField(default=False)),
                ('alerta_interna', models.BooleanField(default=False)),
                ('notificacion_paciente', models.BooleanField(default=False)),
                ('notificacion_profesional', models.BooleanField(default=False)),
                ('dias_bloqueo', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
