# Generated by Django 5.2.6 on 2025-10-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
        ('no_show_policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicanoshow',
            name='empresa_id',
        ),
        migrations.AddField(
            model_name='politicanoshow',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AddField(
            model_name='politicanoshow',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multas_no_show', to='api.usuario'),
            preserve_default=False,
        ),
    ]
