# Generated by Django 5.2.6 on 2025-10-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
        ('no_show_policies', '0002_remove_politicanoshow_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicanoshow',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
