# Generated by Django 5.2.6 on 2025-10-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_show_policies', '0003_alter_politicanoshow_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicanoshow',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
