# Generated by Django 5.2.6 on 2025-10-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no_show_policies', '0004_politicanoshow_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicanoshow',
            name='usuario',
        ),
    ]
