# Generated by Django 5.2.6 on 2025-10-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
        ('no_show_policies', '0005_remove_politicanoshow_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicanoshow',
            name='estado_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadodeconsulta'),
        ),
    ]
