# Generated by Django 5.2.6 on 2025-10-13 14:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_stripe_fields_to_empresa'),
        ('no_show_policies', '0006_alter_politicanoshow_estado_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.consulta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.empresa')),
                ('politica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_aplicadas', to='no_show_policies.politicanoshow')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='api.usuario')),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('consulta', 'politica'), name='uniq_multa_por_consulta_y_politica')],
            },
        ),
    ]
