# Generated by Django 5.2.6 on 2025-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdominio para acceso multi-tenant (ej: clinica1, clinica2)', max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID del cliente en Stripe', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción en Stripe', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Indica si es el dominio público para administración')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'api_empresa',
                'ordering': ['nombre'],
            },
        ),
    ]
