# Generated by Django 5.2.6 on 2025-10-15 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Estadodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_consulta', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'estadodeconsulta',
            },
        ),
        migrations.CreateModel(
            name='Estadodefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_factura', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'estadodefactura',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='tenancy.empresa')),
                ('idestadofactura', models.ForeignKey(db_column='idestadofactura', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.estadodefactura')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('motivoconsulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('episodio', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'historialclinico',
                'ordering': ['-fecha', '-episodio'],
            },
        ),
        migrations.CreateModel(
            name='Documentoadjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredocumento', models.CharField(max_length=255)),
                ('rutaarchivo', models.CharField(max_length=512)),
                ('fechacreacion', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentosAdjuntos', to='tenancy.empresa')),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.historialclinico')),
            ],
            options={
                'db_table': 'documentoadjunto',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('unidaddemedida', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Itemdefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsFacturas', to='tenancy.empresa')),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.factura')),
            ],
            options={
                'db_table': 'itemdefactura',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidadmiligramos', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('experienciaprofesional', models.TextField(blank=True, null=True)),
                ('nromatricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontologos', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'odontologo',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='tenancy.empresa')),
                ('idestadoconsulta', models.ForeignKey(db_column='idestadoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.estadodeconsulta')),
                ('idhorario', models.ForeignKey(db_column='idhorario', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.horario')),
                ('cododontologo', models.ForeignKey(blank=True, db_column='cododontologo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.odontologo')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.usuario')),
                ('carnetidentidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='pacientecodigo',
            field=models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historias', to='clinic.paciente'),
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('radiografia', 'Radiografía'), ('examen_laboratorio', 'Examen de Laboratorio'), ('imagen_diagnostico', 'Imagen de Diagnóstico'), ('consentimiento', 'Consentimiento Informado'), ('receta', 'Receta Médica'), ('foto_clinica', 'Foto Clínica'), ('otro', 'Otro')], max_length=50)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_s3', models.CharField(max_length=500)),
                ('s3_key', models.CharField(max_length=500)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('fecha_documento', models.DateField(help_text='Fecha del documento médico')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='tenancy.empresa')),
                ('idconsulta', models.ForeignKey(blank=True, db_column='idconsulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='clinic.consulta')),
                ('profesional_carga', models.ForeignKey(db_column='profesional_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to='users.usuario')),
                ('idhistorialclinico', models.ForeignKey(blank=True, db_column='idhistorialclinico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_s3', to='clinic.historialclinico')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='clinic.paciente')),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
                'db_table': 'documento_clinico',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='codpaciente',
            field=models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.paciente'),
        ),
        migrations.CreateModel(
            name='Piezadental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepieza', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_dentales', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'piezadental',
            },
        ),
        migrations.CreateModel(
            name='Plandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaplan', models.DateField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montototal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cododontologo', models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.paciente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planesTratamientos', to='tenancy.empresa')),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.estado')),
            ],
            options={
                'db_table': 'plandetratamiento',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='idplantratamiento',
            field=models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.plandetratamiento'),
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto_contenido', models.TextField()),
                ('firma_base64', models.TextField(help_text='Firma del paciente guardada en formato Base64')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField()),
                ('pdf_firmado', models.BinaryField(help_text='PDF del consentimiento con firma digital', null=True)),
                ('hash_documento', models.CharField(help_text='Hash SHA-256 del documento firmado', max_length=64, null=True)),
                ('fecha_hora_sello', models.DateTimeField(help_text='Fecha y hora del sellado digital', null=True)),
                ('fecha_validacion', models.DateTimeField(help_text='Fecha y hora de validación', null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='tenancy.empresa')),
                ('validado_por', models.ForeignKey(help_text='Usuario que validó el consentimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_validados', to='users.usuario')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='clinic.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='clinic.paciente')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='clinic.plandetratamiento')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'db_table': 'api_consentimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.usuario')),
                ('habilidadessoftware', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionistas', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'recepcionista',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='codrecepcionista',
            field=models.ForeignKey(blank=True, db_column='codrecepcionista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.recepcionista'),
        ),
        migrations.CreateModel(
            name='Recetamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('cododontologo', models.ForeignKey(db_column='cododontologo', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.paciente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'recetamedica',
            },
        ),
        migrations.CreateModel(
            name='Imtemreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologia', models.TextField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsReceta', to='tenancy.empresa')),
                ('idmedicamento', models.ForeignKey(db_column='idmedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.medicamento')),
                ('idreceta', models.ForeignKey(db_column='idreceta', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.recetamedica')),
            ],
            options={
                'db_table': 'itemreceta',
            },
        ),
        migrations.CreateModel(
            name='Registroodontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrosOdontogramas', to='tenancy.empresa')),
                ('idhistorialclinico', models.ForeignKey(db_column='idhistorialclinico', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.historialclinico')),
                ('idpiezadental', models.ForeignKey(db_column='idpiezadental', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.piezadental')),
            ],
            options={
                'db_table': 'registroodontograma',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costobase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Itemplandetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costofinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsPlanesTratamientos', to='tenancy.empresa')),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.estado')),
                ('idpiezadental', models.ForeignKey(blank=True, db_column='idpiezadental', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.piezadental')),
                ('idplantratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.plandetratamiento')),
                ('idservicio', models.ForeignKey(db_column='idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.servicio')),
            ],
            options={
                'db_table': 'itemplandetratamiento',
            },
        ),
        migrations.CreateModel(
            name='Tipodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconsulta', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consulta', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'tipodeconsulta',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='idtipoconsulta',
            field=models.ForeignKey(db_column='idtipoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.tipodeconsulta'),
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pago', to='tenancy.empresa')),
            ],
            options={
                'db_table': 'tipopago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenancy.empresa')),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.factura')),
                ('idtipopago', models.ForeignKey(db_column='idtipopago', on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.tipopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddConstraint(
            model_name='historialclinico',
            constraint=models.UniqueConstraint(fields=('pacientecodigo', 'episodio'), name='uniq_historial_paciente_episodio'),
        ),
    ]
